"""Enhance rationales for section 03 — Key Clinical Processes in Lifestyle Medicine."""
import json
from pathlib import Path

FILE = Path("data/consolidated/03-key-clinical-processes-in-lifestyle-medicine.json")

ENHANCED = {
    "00097": "C is correct: The ACLM recommends HbA1c, not just fasting glucose, as the basis for medication adjustments in type 2 diabetes; a 3-month recheck confirms sustained metabolic improvement before reducing medications. A is incorrect: Abruptly discontinuing metformin is unsafe without confirmed HbA1c normalisation and sustained lifestyle response. B is incorrect: Reducing the dose by half is premature when the full response has not yet been measured by HbA1c. D is incorrect: Increasing metformin when glucose is already improving and the patient wishes to reduce medications contradicts both the clinical goal and the ACLM's remission-focused approach.",

    "00098": "C is correct: The ability to extract data on lifestyle vital signs and interventions enables quality improvement, cost-savings analysis, and demonstration of the impact of lifestyle medicine practices on patient outcomes. A is incorrect: Automatic prompts for annual physicals support preventive care scheduling but do not track the effectiveness of lifestyle interventions. B is incorrect: Integration with billing software improves financial operations but provides no insight into lifestyle vital signs or intervention outcomes. D is incorrect: A patient portal for appointment scheduling improves access but does not help monitor or analyse lifestyle medicine intervention effectiveness.",

    "00099": "C is correct: Resistance training 2–3 days per week complements the patient's existing aerobic routine by increasing muscle mass, resting energy expenditure, and reducing fall risk, providing additive cardiovascular benefit after myocardial infarction. A is incorrect: Doubling walking time to 60 minutes adds aerobic volume but does not address the muscle-strengthening component that resistance training uniquely provides. B is incorrect: High-intensity interval training carries higher cardiovascular demand and is not the recommended next step for a patient newly completing cardiac rehabilitation. D is incorrect: Daily yoga has flexibility and stress benefits but lacks the cardiovascular and metabolic impact of resistance training in this clinical context.",

    "00100": "C is correct: The Plan phase of the PDSA cycle begins by setting a specific, measurable goal (e.g., \"90% of charts contain lifestyle vital sign data\"), which provides the target against which improvement will be evaluated in the Study phase. A is incorrect: Implementing a new EHR template is a Do phase action that should follow, not precede, goal-setting. B is incorrect: Staff training is a supporting activity that occurs within the Do phase, after the plan and goal have been established. D is incorrect: Analysing current rates informs the plan but is not itself the first PDSA step, which is defining the specific improvement goal.",

    "00101": "C is correct: Changes in metabolic parameters such as blood pressure, lipids, and HbA1c directly measure the health impact of group visits and align with the core goal of lifestyle medicine to improve clinical outcomes. A is incorrect: Patient satisfaction scores are valuable secondary measures but do not directly reflect the physiological effectiveness of the metabolic syndrome intervention. B is incorrect: Attendance numbers measure engagement, not health outcomes; a well-attended but ineffective programme would still score well on this metric. D is incorrect: Revenue generated reflects financial performance, not patient health improvement, and is an inappropriate primary outcome for a clinical effectiveness assessment.",

    "00102": "C is correct: A whole food plant-based dietary pattern has stronger evidence than the Mediterranean diet for reducing blood pressure and promoting weight loss, and is the pattern recommended by ACLM for optimal cardiovascular and metabolic outcomes. A is incorrect: The patient is already following a Mediterranean diet, which is relatively low in saturated fat; further reductions within the same pattern are unlikely to produce meaningful additional blood pressure reduction. B is incorrect: Increasing protein intake is not a recognised evidence-based strategy for lowering blood pressure and does not address the dietary shift needed for optimal control. D is incorrect: Intermittent fasting may assist with weight loss in some contexts but lacks robust evidence for blood pressure reduction comparable to a whole food plant-based diet.",

    "00103": "C is correct: The ACLM defines diabetes reversal as achieving an HbA1c below the diabetic threshold of 6.5% without the use of diabetes medications, sustained for at least 3 months to confirm durability rather than transient improvement. A is incorrect: Achieving HbA1c < 6.5% while still on metformin does not constitute remission because the medication continues to contribute to glucose control. B is incorrect: Fasting glucose < 126 mg/dL for 3 months is not the ACLM's definition; remission requires HbA1c below the diabetic threshold off medications. D is incorrect: Patient-reported resolution of symptoms is subjective and unreliable; HbA1c is the validated biochemical standard for defining remission.",

    "00104": "D is correct: The six key elements of the Chronic Care Model are self-management support, decision support, delivery system design, clinical information systems, health systems, and community resources. Pharmaceutical intervention is not among them. A is incorrect: Self-management support is explicitly one of the six core elements of the Chronic Care Model. B is incorrect: Decision support is one of the six core elements, helping clinicians follow evidence-based guidelines. C is incorrect: Delivery system design is one of the six core elements, addressing how care is organised and delivered.",

    "00105": "B is correct: The INTERHEART study identified smoking, dyslipidaemia, hypertension, diabetes, and abdominal obesity as the five factors accounting for approximately 80% of the population-attributable risk for acute myocardial infarction worldwide. A is incorrect: This combination omits dyslipidaemia and incorrectly substitutes physical inactivity, making it an incomplete representation of the five INTERHEART risk factors responsible for 80% of attributable risk. C is incorrect: While alcohol, physical inactivity, poor diet, and psychosocial factors are among the nine INTERHEART risk factors, this combination does not represent the five that account for 80% of the attributable risk. D is incorrect: Family history and chronic kidney disease are not among the nine modifiable INTERHEART risk factors; this combination misrepresents the study's findings.",

    "00106": "D is correct: The work of Caldwell Esselstyn and Dean Ornish demonstrated that a low-fat, whole food plant-based dietary pattern—minimising high-fat plant foods, salt, and caffeine while emphasising leafy greens—is the only eating style with evidence for reversing coronary artery disease. A is incorrect: The Mediterranean diet has strong evidence for cardiovascular prevention but has not been shown to reverse established coronary artery disease. B is incorrect: The DASH diet is evidence-based for blood pressure reduction but has not demonstrated reversal of coronary atherosclerosis in clinical trials. C is incorrect: A ketogenic diet is high in fat and lacks evidence for reversing coronary artery disease; the diets shown to reverse CAD are specifically low in fat.",

    "00107": "A is correct: Current guidelines recommend an initial weight loss goal of 5–10% of initial body weight, as this modest reduction produces clinically significant improvements in cardiovascular risk factors, glycaemic control, and all-cause mortality. B is incorrect: A 10–15% initial target exceeds standard first-line recommendations and may be appropriate as a subsequent goal but is not the recommended starting target. C is incorrect: A 15–20% initial goal is beyond standard guideline recommendations for the initial weight loss target in obesity management. D is incorrect: A 20–25% initial goal is unrealistic as a first target and is not supported by current obesity management guidelines.",

    "00108": "B is correct: Current guidelines support bariatric surgery for individuals with BMI ≥ 40 kg/m² or BMI ≥ 35 kg/m² with at least one obesity-associated comorbidity; this patient meets eligibility with BMI 35.4 kg/m² and type 2 diabetes as a qualifying comorbidity. A is incorrect: BMI ≥ 30 kg/m² with poorly controlled diabetes is not sufficient on its own to meet standard bariatric surgery criteria, which require BMI ≥ 35 with comorbidity or ≥ 40 regardless of comorbidities. C is incorrect: While BMI ≥ 40 qualifies independently, this patient's BMI of 35.4 means the correct criterion is the comorbidity threshold, not the independent high-BMI criterion. D is incorrect: Failure to achieve 5% weight loss after 6 months of lifestyle intervention is not a recognised standalone criterion for bariatric surgery eligibility in current guidelines.",

    "00109": "B is correct: The step test is the most practical option for a typical office setting as it requires minimal equipment, can be performed in a confined space, and provides a validated estimate of cardiorespiratory fitness. A is incorrect: Treadmill stress tests require specialised equipment and significant space, and are typically performed in exercise physiology or cardiology settings rather than a standard office. C is incorrect: The 6-minute walk test is used primarily in pulmonary and cardiac rehabilitation settings and requires a measured corridor of at least 30 metres, making it unsuitable for a typical office environment. D is incorrect: Cycle ergometer tests require specialised equipment and are not standard in a typical primary care office setting.",

    "00110": "B is correct: The Diabetes Prevention Program (DPP) found that intensive lifestyle intervention reduced diabetes incidence by 58% versus placebo, making it more effective than metformin, which reduced incidence by 31%. A is incorrect: Metformin 850 mg twice daily reduced diabetes incidence by 31%—significant, but less effective than the intensive lifestyle intervention in the DPP. C is incorrect: The combination of metformin and lifestyle intervention was not the arm that showed greatest benefit; lifestyle intervention alone outperformed metformin. D is incorrect: Standard lifestyle recommendations plus placebo served as the control condition and produced the least reduction in diabetes incidence in the DPP.",

    "00111": "C is correct: The Single-Item Sleep Quality Scale consists of one question asking patients to rate their overall sleep quality on a scale of 1 to 10, making it the most efficient tool for a quick primary care assessment during a routine visit. A is incorrect: The Pittsburgh Sleep Quality Index (PSQI) is a comprehensive 19-item questionnaire that provides detailed sleep quality data but is too lengthy for routine use in a busy primary care setting. B is incorrect: The Epworth Sleepiness Scale assesses daytime sleepiness specifically rather than overall sleep quality, making it less appropriate for a general sleep quality screen. D is incorrect: The Insomnia Severity Index focuses specifically on insomnia symptoms and severity rather than providing a broad overall sleep quality assessment.",

    "00112": "B is correct: A 2011 meta-analysis of over 12,000 women with breast cancer found regular physical activity associated with a 34% reduction in breast cancer mortality, a 24% reduction in recurrence, and a 41% reduction in all-cause mortality—the strongest evidence for any single lifestyle intervention in this population. A is incorrect: A ketogenic diet lacks robust evidence for improving survival or reducing recurrence in breast cancer; no comparable meta-analysis supports it as a primary intervention in this context. C is incorrect: High-dose antioxidant supplements have not demonstrated improved survival in breast cancer patients and may interfere with some cancer treatments. D is incorrect: Daily meditation may benefit quality of life and psychological wellbeing but lacks evidence of the survival benefit magnitude demonstrated for physical activity in breast cancer patients.",

    "00113": "C is correct: The PSS-4 is a 4-item shortened version of the PSS-10 that is efficient, validated, and easy to administer during a routine primary care visit, making it the most appropriate brief perceived-stress assessment tool in this setting. A is incorrect: The PSS-10, while more comprehensive, consists of 10 items and takes longer to complete, reducing its feasibility for rapid screening during a routine visit. B is incorrect: The Holmes-Rahe Stress Inventory measures life event stress over the past year rather than perceived stress, and is more time-consuming and less suited to a brief primary care screen. D is incorrect: The DASS-21 is a 21-item tool that measures depression, anxiety, and stress simultaneously; it is too lengthy for a brief perceived-stress-specific screen.",

    "00114": "D is correct: Photograph-assisted dietary assessment is more accurate than self-reported methods because it reduces underreporting of consumed foods—a common problem in people trying to lose weight—by providing an objective, visual record of actual intake. A is incorrect: A 24-hour dietary recall relies entirely on patient memory and is subject to significant recall bias and underreporting, especially in individuals motivated to present favourably. B is incorrect: A food frequency questionnaire captures habitual dietary patterns but relies on self-report and is subject to the same underreporting biases, making it less accurate than photo-assisted assessment. C is incorrect: A 3-day food diary improves on single-day recall but still depends on self-report and remains prone to underreporting, particularly in individuals trying to lose weight.",

    "00115": "B is correct: The Physical Activity Vital Sign (PAVS) consists of two validated questions about the frequency and duration of moderate to strenuous exercise, making it the only formally validated traditional vital sign for physical activity assessment in clinical practice. A is incorrect: The IPAQ is a validated self-report instrument for research purposes but is not considered a formally validated traditional clinical vital sign in the same way as the PAVS. C is incorrect: The GPAQ is used in public health surveillance and research contexts but has not been validated as a traditional clinical vital sign the way the PAVS has. D is incorrect: The Godin-Shephard Leisure-Time Physical Activity Questionnaire assesses leisure-time activity but is a research instrument, not a formally validated clinical vital sign.",

    "00116": "D is correct: The ACLM recommends a low-fat whole food plant-based dietary pattern, as demonstrated by Esselstyn and Ornish, as the only eating style with evidence for reversing coronary artery disease, including regression of existing atherosclerotic plaques. A is incorrect: A low-fat vegetarian diet that includes dairy and eggs has not been specifically shown in trials to reverse coronary artery disease to the same degree as the specific whole food plant-based protocol. B is incorrect: The Mediterranean diet has strong evidence for cardiovascular prevention and risk factor reduction but has not been shown to reverse established coronary atherosclerotic plaques. C is incorrect: The DASH diet is primarily evidence-based for blood pressure reduction and general cardiovascular risk, not for reversal of existing coronary artery disease.",

    "00117": "C is correct: In the PDSA cycle, after the Study phase reveals incomplete implementation, the Act phase requires analysing root causes and designing a targeted intervention before making further changes, rather than abandoning or expanding the protocol prematurely. A is incorrect: Abandoning the protocol without understanding the causes of non-compliance discards potentially valuable improvements and does not address the underlying barrier. B is incorrect: Implementing a new EHR alert system introduces another change before the reason for incomplete screening is understood, which may not address the actual problem. D is incorrect: Expanding the protocol to capture additional lifestyle factors while the current one is underperforming compounds the problem rather than resolving the fundamental implementation issue.",

    "00118": "C is correct: Longitudinal reporting on lifestyle vital signs allows practitioners to track trends in key health indicators over time, evaluate whether interventions are producing results, and make data-driven adjustments to individual treatment plans. A is incorrect: Automated appointment reminders improve adherence to scheduled visits but provide no data on the effectiveness of lifestyle interventions between appointments. B is incorrect: Billing software integration optimises revenue cycle management and has no function in tracking or reporting patient lifestyle health outcomes. D is incorrect: Online appointment scheduling improves patient access and convenience but contributes nothing to monitoring or evaluating lifestyle intervention effectiveness.",

    "00119": "C is correct: Current physical activity guidelines recommend at least 150 minutes of moderate-intensity aerobic activity per week for adults, as reflected in both the PAVS assessment framework and national guidelines. A is incorrect: 75 minutes per week is the recommendation for vigorous-intensity aerobic activity, not moderate-intensity; the two categories have different time thresholds. B is incorrect: 100 minutes per week is not a recognised guideline recommendation for either moderate or vigorous aerobic activity. D is incorrect: 200 minutes per week exceeds the minimum recommended threshold; while more activity generally provides greater benefit, 200 minutes is not the standard guideline recommendation.",

    "00120": "C is correct: SMAs complement rather than replace individual care; patients with complex or sensitive issues still require personalised one-on-one follow-up, so SMAs do not reduce the overall need for individual appointments. A is incorrect: Increased time for patient education is a recognised benefit of SMAs because the group format allows more educational content than a standard individual visit. B is incorrect: Improved peer support is a well-documented benefit of SMAs, as patients learn from shared experiences and feel supported by others with similar conditions. D is incorrect: More efficient use of provider time per patient is a recognised benefit of SMAs, allowing the clinician to reach more patients simultaneously.",

    "00121": "C is correct: This team composition comprehensively addresses the patient's three conditions through lifestyle medicine: the physician provides medical oversight, the registered dietitian addresses nutrition, the exercise physiologist prescribes physical activity, and the health coach supports sustainable behaviour change. A is incorrect: A physician, endocrinologist, and nutritionist focus primarily on diabetes management and do not provide the physical activity or behaviour change support needed for comprehensive lifestyle medicine management of all three conditions. B is incorrect: While a pharmacist adds medication management expertise, this team lacks the dedicated exercise physiology and nutrition support needed for lifestyle-based management of obesity, diabetes, and hypertension. D is incorrect: An endocrinologist, cardiologist, and bariatric surgeon represent a specialist-and-procedure model rather than a lifestyle medicine interdisciplinary team and do not address the behaviour change needs of this patient.",

    "00122": "B is correct: Patient activation refers specifically to a patient's knowledge, skills, and confidence in managing their own health and healthcare—the degree to which they take an active role in their own health improvement. A is incorrect: Scheduling follow-up appointments is an administrative function performed by clinic staff and does not represent the patient-centred concept of activation. C is incorrect: Prescribing medication is a clinician action and does not relate to the patient's own knowledge, skills, or confidence in self-management. D is incorrect: Referring a patient to a specialist is a clinical decision made by the provider and is not an element of patient activation, which focuses on the patient's own capabilities and engagement.",

    "00123": "B is correct: The PAM is specifically designed to measure a patient's knowledge, skills, and confidence in managing their own health and healthcare, making it the validated tool of choice for assessing patient engagement and activation in lifestyle medicine. A is incorrect: The SF-36 is a general health-related quality of life measure and does not specifically assess a patient's activation level or capacity to self-manage. C is incorrect: The EQ-5D measures health status across five dimensions for health economic purposes and does not assess patient engagement or activation in self-management. D is incorrect: The HLQ measures health literacy across multiple domains but does not specifically quantify a patient's confidence, knowledge, or skills in managing their own health as the PAM does.",

    "00124": "D is correct: SMAs increase, not decrease, opportunities for patient education by providing more time for educational content in a group format; decreased need for patient education is therefore the opposite of what SMAs achieve. A is incorrect: Improved access to care is a recognised benefit of SMAs, as group visits can accommodate more patients in available appointment slots. B is incorrect: Increased patient and provider satisfaction is a well-documented benefit of SMAs for both parties. C is incorrect: Reduced costs and increased income are reported operational benefits of SMAs due to the efficiency of seeing multiple patients simultaneously.",

    "00125": "C is correct: Self-management support is a core element of the Chronic Care Model that involves equipping patients and families with skills and confidence to manage chronic conditions, including providing tools and regularly assessing progress. A is incorrect: Increased specialist referrals is not an element of the Chronic Care Model, which emphasises proactive team-based primary care rather than specialist-dependent reactive care. B is incorrect: Acute care management is the opposite of the Chronic Care Model's orientation, which focuses on planned, proactive management of ongoing conditions rather than episodic acute responses. D is incorrect: Pharmaceutical interventions are not one of the six defined elements of the Chronic Care Model, though medications may feature within the broader care provided.",

    "00126": "C is correct: The Study phase of the PDSA cycle involves systematically analysing the data collected during the Do phase to determine whether the change produced the desired improvement and to identify what should be modified in the next cycle. A is incorrect: Implementing the new intervention occurs in the Do phase, not the Study phase. B is incorrect: Training staff may occur as part of the Do phase or as preparation within the Plan phase, not during the Study phase. D is incorrect: Developing a specific improvement goal is the work of the Plan phase, which precedes implementation and analysis.",

    "00127": "B is correct: The AUDIT-C is a brief 3-question screening tool that is more concise than the full AUDIT and more sensitive than the CAGE questionnaire for identifying risky or hazardous drinking in a primary care setting. A is incorrect: The CAGE questionnaire is a 4-item tool focused on dependence indicators but has lower sensitivity than the AUDIT-C for detecting hazardous drinking that does not meet dependence criteria. C is incorrect: The Michigan Alcohol Screening Test (MAST) is a longer instrument designed to identify alcoholism rather than provide a brief screen for risky drinking in general primary care. D is incorrect: The full AUDIT is a 10-item questionnaire that provides comprehensive alcohol use assessment but is too lengthy for brief screening in a primary care visit; the AUDIT-C is its validated short form.",

    "00128": "D is correct: SMAs increase, not decrease, opportunities for peer support because the group format allows patients to hear each other's questions, share experiences, and feel supported by others facing similar challenges. A is incorrect: Improved access to care is a recognised benefit of SMAs, allowing more patients to be seen in available clinical time. B is incorrect: Increased patient and provider satisfaction is a well-documented benefit of SMAs for both parties. C is incorrect: While SMAs do not eliminate the need for individual care, they do improve overall access; the suggestion that they reduce peer support is directly contrary to a core benefit of the group format.",

    "00575": "C is correct: The Ornish Lifestyle Heart Trial demonstrated that a comprehensive programme including a low-fat vegetarian diet, aerobic exercise, stress management, and group psychosocial support produced significant reductions in LDL cholesterol and anginal episodes at one year, with even greater regression of coronary atherosclerosis at five years. A is incorrect: Low-fat diet and moderate exercise alone, without the stress management and group support components, represent a less intensive programme and have not been shown to reverse coronary atherosclerosis to the same degree. B is incorrect: The Mediterranean diet and daily yoga have not been studied as a combination in trials demonstrating reversal of coronary heart disease and differ from the specific components of the Ornish programme. D is incorrect: A ketogenic diet is high in fat and lacks evidence for reversing coronary artery disease; high-intensity interval training has not been evaluated in the context of CAD reversal in this manner.",

    "00576": "B is correct: The DIRECT trial demonstrated that 46% of participants achieved remission to a non-diabetic state off antidiabetic drugs at 12 months through an intensive weight management programme, establishing intensive lifestyle intervention as a practical primary care target for diabetes remission. A is incorrect: Bariatric surgery can achieve diabetes remission but is invasive and typically reserved for patients with severe obesity or failed conservative management; it is not the first-line approach for a newly diagnosed patient. C is incorrect: Metformin is a common first-line pharmacological treatment for type 2 diabetes but produces glucose control rather than remission, and does not achieve remission rates comparable to intensive lifestyle intervention. D is incorrect: Intermittent fasting may produce short-term weight and glucose benefits but has not been demonstrated to achieve diabetes remission at rates comparable to the comprehensive weight management programme used in the DIRECT trial.",

    "00577": "C is correct: Jenkins et al. (2003) demonstrated that a dietary portfolio emphasising plant sterols, viscous fibres, soy protein, and nuts produced an average LDL reduction of 28.6%, which was not significantly different from the 30.9% reduction achieved by statin therapy, offering a comparable dietary alternative. A is incorrect: A low-carbohydrate, high-fat diet has not been shown to produce LDL reductions comparable to statin therapy and may raise LDL in some individuals. B is incorrect: The Mediterranean diet with olive oil supplementation has cardiovascular benefits and reduces events, but its LDL-lowering effect is not equivalent to statin therapy. D is incorrect: A Paleolithic diet rich in lean meats and vegetables has not been demonstrated to lower LDL cholesterol to an extent comparable to statin therapy.",

    "00578": "C is correct: The meta-epidemiological study by Naci and Ioannidis (2013) found that exercise interventions were statistically no different from drug interventions for secondary prevention of coronary heart disease (OR 0.94), supporting exercise as a comparable alternative to medication in this population. A is incorrect: Exercise was not superior to drug interventions across all cardiovascular conditions; it was more effective than drugs for stroke rehabilitation but less effective than diuretics for heart failure, showing condition-specific variation. B is incorrect: The study's findings directly contradict the claim that drugs are always more effective; exercise was comparable to drugs for secondary coronary heart disease prevention. D is incorrect: Exercise did not require combination with drug therapy to achieve comparable outcomes; the study demonstrated exercise's independent effectiveness in secondary CHD prevention.",

    "00579": "A is correct: The Diabetes Prevention Program trial demonstrated that intensive lifestyle changes were more effective than metformin in reducing diabetes incidence in high-risk individuals, with a 58% reduction versus 31% for metformin over an average follow-up of 2.8 years. B is incorrect: Metformin therapy reduced diabetes incidence by 31%—significant, but less effective than intensive lifestyle intervention (58% reduction) in the DPP trial. C is incorrect: The specific combination of lifestyle intervention plus metformin was not evaluated as a combined arm in the DPP trial; the individual interventions were compared separately against placebo. D is incorrect: Watchful waiting with annual monitoring is a passive approach that does not actively reduce diabetes incidence and is substantially less effective than either lifestyle intervention or metformin.",

    "00580": "C is correct: The PAVS consists of two validated questions assessing the frequency and duration of moderate to strenuous exercise, making it the appropriate tool to determine this patient's current physical activity level before recommending an increase in activity. A is incorrect: The AUDIT-C is a three-question alcohol use screening tool and has no role in assessing physical activity level or readiness for exercise. B is incorrect: The Pittsburgh Sleep Quality Index is a 19-item tool assessing sleep quality and disturbances, which is not relevant to evaluating physical activity readiness. D is incorrect: The Perceived Stress Scale measures psychological stress and is not an appropriate tool for assessing physical activity level or exercise readiness.",

    "00581": "C is correct: The DIRECT (Diabetes Remission Clinical Trial) found that 46% of participants achieved remission to a non-diabetic state off antidiabetic medications at 12 months through intensive lifestyle intervention focused on weight management. A is incorrect: 25% does not reflect the DIRECT trial's 12-month remission rate; this figure significantly underestimates the effectiveness of the intensive lifestyle programme. B is incorrect: 36% does not match the DIRECT trial finding and does not correspond to the published data from this study. D is incorrect: 58% corresponds to the diabetes prevention rate from the DPP trial, not the DIRECT trial remission rate; conflating these two landmark studies would be an error.",

    "00582": "C is correct: The Lifestyle Heart Trial tested a comprehensive programme of a low-fat (10% of calories) vegetarian diet, aerobic exercise, stress management, and group psychosocial support, producing significant reductions in LDL and anginal episodes at one year and greater regression of coronary atherosclerosis at five years. A is incorrect: Low-fat diet and moderate exercise with medication adherence were not the components tested in the Lifestyle Heart Trial, which excluded lipid-lowering medications and required stress management and group support. B is incorrect: Mediterranean diet and yoga were not the interventions studied in the Lifestyle Heart Trial; this combination does not reflect the specific Ornish programme protocol. D is incorrect: A ketogenic diet and high-intensity interval training were not components of the Lifestyle Heart Trial, and a ketogenic diet is incompatible with the low-fat plant-based approach used in the study.",

    "00583": "D is correct: The six key elements of the Chronic Care Model are community resources and policies, health care organisation, self-management support, delivery system design, decision support, and clinical information systems. Pharmaceutical interventions are not among them. A is incorrect: Self-management support is explicitly one of the six core elements of the Chronic Care Model. B is incorrect: Decision support is one of the six core elements, helping clinicians adhere to evidence-based guidelines. C is incorrect: Delivery system design is one of the six core elements, addressing organisation and team roles in care delivery.",

    "00584": "B is correct: The Mediterranean Diet Adherence Screener (MEDAS) is a validated tool specifically designed to measure adherence to the Mediterranean dietary pattern, which includes regular consumption of olive oil, whole grains, fruits, vegetables, legumes, nuts, fish, and wine. A is incorrect: \"Starting the Conversation\" is an eight-item simplified food frequency instrument used for general dietary assessment in primary care, not specifically for measuring Mediterranean diet adherence. C is incorrect: The Dietary History Questionnaire (DHQ) is a comprehensive general dietary assessment tool and is not designed specifically to measure adherence to the Mediterranean dietary pattern. D is incorrect: The ASA24 is an automated 24-hour dietary recall tool that captures detailed intake data but is not specifically designed or validated as a measure of Mediterranean diet adherence.",

    "00585": "C is correct: The PSS uses a 5-point response scale (0 = never to 4 = very often), not a 7-point scale, making the statement that it uses a 7-point scale the false statement among the options. A is incorrect: It is true that the full PSS is a 10-item questionnaire, so this statement is accurate and not the false answer. B is incorrect: It is true that the PSS evaluates perceived stress over the past month, so this statement is accurate and not the false answer. D is incorrect: It is true that a brief 4-item version (PSS-4) exists for quick screening, so this statement is accurate and not the false answer.",

    "00586": "A is correct: Self-management support directly empowers patients with knowledge, skills, and confidence, while delivery system design ensures the practice team is organised and prepared to provide proactive care; together they best represent the productive interaction between an informed patient and a prepared team in the Chronic Care Model. B is incorrect: Decision support and clinical information systems are key Chronic Care Model elements but primarily support clinical decision-making rather than the direct patient-provider interaction described as productive interactions. C is incorrect: Community resources and health care organisation are structural and contextual elements of the model but do not specifically describe the patient-provider interaction at the clinical encounter level. D is incorrect: Health care organisation and self-management support are both Chronic Care Model elements, but health care organisation is a broader structural element; delivery system design more specifically addresses how the practice team prepares for and conducts patient interactions.",

    "00587": "C is correct: A score of 6 on the AUDIT-C indicates higher risk of alcohol misuse requiring more detailed evaluation; the most appropriate next step is to conduct the full 10-item AUDIT to gather comprehensive information before deciding on interventions or referrals. A is incorrect: Brief advice on reducing alcohol consumption may be appropriate for lower-risk patients but is premature before the full extent of alcohol misuse is characterised by a comprehensive assessment. B is incorrect: Referral to an addiction specialist is excessive as a first response to an AUDIT-C score without completing a full AUDIT to determine the severity and nature of the alcohol use problem. D is incorrect: Recommending complete abstinence is an intervention that should be guided by a thorough assessment of dependence and use patterns, not a screening score alone.",

    "00588": "A is correct: The PDSA cycle follows the sequence Plan (develop the plan), Do (implement the change), Study (analyse the results), and Act (determine modifications for the next cycle), which corresponds to developing a plan, implementing changes, analysing results, and modifying the approach. B is incorrect: While analysing current practice may inform the Plan phase, the formal PDSA cycle begins with developing the plan rather than with analysis, making option B's sequence inaccurate. C is incorrect: Beginning with implementation skips the Plan phase and enters at the Do phase, which is not the correct order of the PDSA cycle. D is incorrect: Reviewing current outcomes before developing a plan inverts the PDSA cycle; the cycle begins with planning, not with outcome review.",

    "00589": "B is correct: The patient exercises 30 minutes × 3 days = 90 minutes per week, which falls within the PAVS \"insufficiently active\" category of 1–149 minutes per week of moderate-intensity aerobic activity. A is incorrect: The \"inactive\" category in the PAVS applies to individuals reporting 0 minutes of moderate to strenuous exercise per week; this patient reports 90 minutes, so inactive is incorrect. C is incorrect: The \"sufficiently active\" category requires at least 150 minutes per week; this patient achieves only 90 minutes, falling short of the threshold. D is incorrect: \"Highly active\" would imply exercise well beyond the minimum 150-minute threshold; 90 minutes per week does not meet even the sufficiently active standard.",

    "00590": "C is correct: Research shows that physicians who are actively working to improve their own health habits counsel patients on lifestyle changes significantly more often than physicians who are not attempting to change their health behaviours, even if they have not yet achieved optimal health. A is incorrect: Evidence contradicts the claim that physician health habits have no impact on counselling frequency; studies show a positive association between personal health improvement efforts and patient counselling. B is incorrect: Setting perfect health as a prerequisite for counselling patients is an unrealistic and unsupported standard; physicians who are imperfect but actively improving still counsel patients more effectively. D is incorrect: Patient outcomes in lifestyle medicine are not determined solely by physician knowledge; personal modelling of health behaviour improvement has been shown to independently influence counselling frequency.",

    "00591": "C is correct: The Plan phase of the PDSA cycle involves defining the specific plan including who will collect the data, what will be measured, and when it will occur, along with making predictions—this must occur before any implementation begins. A is incorrect: Starting to collect lifestyle vital signs immediately skips the Plan phase and moves directly to the Do phase without a structured plan, making it an incorrect first step. B is incorrect: Analysing current collection rates formally belongs to the Study phase of a prior cycle, not the first step of the Plan phase in a new cycle. D is incorrect: Training all staff may be part of the implementation (Do phase) but is not the first step; it should occur after the plan—including goals, roles, and timing—has been developed.",

    "00592": "C is correct: The ACC/AHA/TOS 2013 Obesity recommendations endorse referring patients with BMI ≥ 30 to a comprehensive lifestyle intervention programme that integrates caloric restriction, increased physical activity, and behavioural strategies, making this the evidence-based primary approach for sustainable weight loss. A is incorrect: Bariatric surgery is reserved for patients with BMI ≥ 40 or ≥ 35 with comorbidities who have not responded to lifestyle intervention; it is not the primary approach for a patient with BMI 31. B is incorrect: Pharmacotherapy alone is insufficient for sustainable weight loss and is not recommended as a standalone strategy; it is used as an adjunct to lifestyle intervention, not a replacement. D is incorrect: Intermittent fasting may assist weight loss in some individuals but has not been shown to be superior to comprehensive lifestyle intervention programmes and is not endorsed as a primary approach in these guidelines.",

    "00593": "B is correct: \"Starting the Conversation\" is described as an eight-item simplified food frequency instrument designed for use in primary care and health-promotion settings, providing a quick dietary overview during a clinical encounter. A is incorrect: A 24-hour dietary recall is a different tool requiring patients to report everything consumed in the previous 24 hours; \"Starting the Conversation\" is not a recall instrument. C is incorrect: Comprehensive nutrient analysis software performs detailed quantitative nutritional analysis and is not the same as the brief frequency-based \"Starting the Conversation\" instrument. D is incorrect: A 7-day food diary app requires patients to log all intake over one week and is far more detailed and time-intensive than the eight-item \"Starting the Conversation\" tool.",

    "00594": "D is correct: Group medical visits do not eliminate the need for individual follow-up care; each patient's unique and sensitive needs are still addressed individually, and personalised follow-up remains necessary even for participants in group visits. A is incorrect: Improved access to care is a recognised benefit of group medical visits, as the group format allows more patients to be seen within available clinical time. B is incorrect: Increased patient and provider satisfaction is a well-documented benefit of group visits for both parties. C is incorrect: Reduced healthcare expenditures is a reported benefit of group visits due to greater efficiency in delivering care to multiple patients simultaneously.",

    "1066": "B is correct: Addressing a care gap in follow-up after positive AUDIT-C screening requires a systematic approach—standardised EHR templates ensure consistent documentation, provider training improves delivery of brief interventions, and regular audit with feedback closes the quality loop. A is incorrect: Switching to a different alcohol screening tool does not address the identified problem, which is inadequate follow-up after a positive screen, not failure of the screening tool itself. C is incorrect: Universal referral to addiction specialists for all AUDIT-C positive patients is clinically excessive; brief intervention delivered in primary care is the appropriate first-line response for most at-risk drinkers. D is incorrect: Increasing screening frequency to monthly does not address the core problem of poor follow-up and inconsistent counselling for patients who already screen positive.",

    "1067": "C is correct: A medical exercise specialist is trained to design exercise programmes for individuals transitioning from medical conditions or rehabilitation who wish to return to their pre-injury fitness levels, providing the medically informed oversight this post-CABG patient requires. A is incorrect: A personal trainer at a local gym has no specific medical training and is not equipped to manage exercise programming for someone with stable angina transitioning from cardiac rehabilitation. B is incorrect: A physical therapist is most appropriate for acute rehabilitation and restoring function after injury or surgery; ongoing fitness programming after cardiac rehabilitation completion is better suited to a medical exercise specialist. D is incorrect: A health coach supports behaviour change and general wellness goals but lacks the clinical exercise physiology training needed to design a safe, progressive programme for a patient with coronary artery disease.",

    "1068": "D is correct: Combining the \"Starting the Conversation\" tool (quick primary care screen), ASA24 (detailed dietary recall), and photo-based food documentation (addresses underreporting) provides complementary information across different aspects of dietary intake, offering the most comprehensive and valid assessment. A is incorrect: A 24-hour dietary recall and food frequency questionnaire are both self-report tools that provide useful data but lack the objectivity of photo-based documentation and the validated primary care screening function of \"Starting the Conversation.\" B is incorrect: \"Starting the Conversation\" and specific nutrient tracking provide a quick screen and quantitative data but do not include a detailed recall or an objective method to reduce underreporting. C is incorrect: The Mediterranean Diet Adherence Screener alone assesses adherence to one specific dietary pattern and cannot provide comprehensive information about overall dietary habits across all food groups.",

    "1069": "C is correct: Based on models like the Ornish Lifestyle Medicine programme, the most effective interdisciplinary team includes specialists covering all aspects of lifestyle medicine—nutrition (dietitian, chef), physical activity (exercise physiologist), stress management, and behavioural support (health coach, group specialist)—providing comprehensive care. A is incorrect: A physician, nurse, and medical assistant represent a standard primary care team without the lifestyle medicine specialisation needed for comprehensive dietary, physical activity, and behaviour change support. B is incorrect: A physician, exercise physiologist, dietitian, and health coach is a strong lifestyle medicine team but lacks dedicated stress management and group support specialists that evidence-based models include. D is incorrect: A physician and two health coaches lack the clinical specialisation in nutrition, exercise physiology, and stress management required for comprehensive lifestyle medicine care.",

    "1070": "B is correct: The HEALM framework recognises that traditional evidence hierarchies, by prioritising RCTs, may undervalue long-term observational studies that are uniquely positioned to capture the cumulative lifetime effects of health behaviours that cannot be studied in short-term controlled trials. A is incorrect: RCTs are valuable and HEALM does not claim they provide the only valid evidence; the framework explicitly acknowledges multiple forms of evidence including observational studies. C is incorrect: Meta-analyses are applicable to lifestyle medicine research; HEALM does not exclude them, and many lifestyle medicine conclusions are drawn from meta-analyses. D is incorrect: Case studies provide the lowest level in traditional evidence hierarchies; HEALM does not promote them to the strongest level of evidence for lifestyle interventions.",

    "1071": "C is correct: A comprehensive stress assessment should evaluate multiple domains including depression (PHQ-2), anxiety (GAD-2), perceived stress (PSS-4), life satisfaction (abbreviated SWLS), and social connectedness (Loma Linda Social Relationship questionnaire), as each captures a distinct aspect of stress and wellbeing. A is incorrect: PHQ-2 and GAD-2 alone screen only for depression and anxiety symptoms; they omit perceived stress, life satisfaction, and social support, which are essential components of a comprehensive stress and wellbeing assessment. B is incorrect: The 4-item PSS and PHQ-9 together assess perceived stress and depression in more detail but still miss anxiety-specific screening, life satisfaction, and social relationship evaluation. D is incorrect: The full PHQ-9 alone is a depression severity scale; it does not assess anxiety, perceived stress, life satisfaction, or social support, making it insufficient as a comprehensive stress assessment protocol.",

    "1072": "B is correct: Training primary care physicians in behavioural counselling techniques and equipping them with practical tools and resources for weight-related care directly addresses the counselling barrier, improving both willingness and competence to discuss weight management with patients. A is incorrect: BMI-based automatic referrals bypass the counselling barrier rather than addressing it and do not build provider capacity to discuss weight with patients. C is incorrect: Requiring providers to maintain a normal BMI is discriminatory, unenforceable, and misidentifies the source of the problem, which is inadequate training rather than provider weight. D is incorrect: Assigning patients only to lower-BMI providers is inappropriate and discriminatory; it does not address the core issue of inadequate training in weight-related counselling.",

    "1073": "B is correct: The direct primary care model with membership fees allows for comprehensive lifestyle medicine services, longer visits, reduced administrative burden from insurance billing, and flexibility to offer additional services like fitness classes and cooking demonstrations, balancing access, quality, and sustainability. A is incorrect: Traditional fee-for-service incentivises high visit volume over comprehensive lifestyle counselling, limiting time for the longer visits and additional services that lifestyle medicine requires. C is incorrect: Concierge practices with dual billing add administrative complexity and may restrict access for those unable to pay membership fees. D is incorrect: A virtual-only pay-per-visit model limits the ability to deliver hands-on assessments, group visits, and cooking or fitness demonstrations that are central to comprehensive lifestyle medicine programmes.",

    "1074": "C is correct: Selecting body composition assessment methods in a clinical setting requires evaluating accuracy, operator dependence, cost, portability, and appropriateness for the specific clinical setting, as each method has different strengths and limitations across these dimensions. A is incorrect: Cost and ease of use alone are insufficient criteria; accuracy and clinical appropriateness must also be considered to ensure the selected method provides clinically valid and actionable data. B is incorrect: Accuracy and patient comfort, while important, do not address practical considerations such as cost, portability, and operator dependence that determine feasibility in a given clinical environment. D is incorrect: Patient preference and insurance coverage do not constitute a clinically rigorous framework for selecting a body composition measurement method; technical and practical factors must take precedence.",

    "1075": "D is correct: Effective population health management using lifestyle vital signs requires structured data collection for consistency, automated risk stratification to identify high-risk patients, population analytics for programme evaluation, provider dashboards for actionable feedback, and patient-facing tools to support engagement. A is incorrect: Basic data entry fields and simple reports provide minimal functionality and cannot support the automated analysis, risk stratification, or population-level insights required for effective lifestyle medicine data use. B is incorrect: Automated data collection and annual summary reports provide some efficiency but lack real-time risk stratification, provider dashboards, and patient engagement tools needed for comprehensive management. C is incorrect: Integration with patient portals and mobile apps improves patient engagement but without structured data collection, risk stratification, and provider-facing analytics, population health management remains limited.",

    "1194": "C is correct: CMS chronic care management services require patients to have two or more chronic conditions expected to last at least 12 months or until death that place the patient at significant risk of death, acute exacerbation, or functional decline, along with establishment of a comprehensive care plan. A is incorrect: One chronic condition lasting 6 months does not meet the CMS criteria, which require at least two chronic conditions with a minimum duration of 12 months or until death. B is incorrect: Two chronic conditions with minimal risk of functional decline do not qualify; the CMS criteria specifically require significant risk of death, exacerbation, or functional decline as a defining feature. D is incorrect: Three acute conditions requiring frequent monitoring do not meet the CMS chronic care management criteria, which are specifically defined by chronicity lasting 12+ months and the risk profile described.",

    "1195": "C is correct: ApoB is a structural protein present on all potentially atherogenic lipoproteins—including LDL, IDL, VLDL, Lp(a), and chylomicrons—and counts the number of atherogenic particles rather than their cholesterol concentration, making it a stronger predictor of cardiovascular risk than LDL-C alone. A is incorrect: ApoB is not limited to measuring LDL particle number; it is present on all atherogenic lipoprotein particles including VLDL, IDL, and Lp(a), making it a broader atherogenicity measure than LDL alone. B is incorrect: ApoB is more predictive of cardiovascular risk than LDL-C alone because it counts all atherogenic particles and reflects particle number rather than cholesterol mass, which is a more direct driver of atherosclerosis. D is incorrect: ApoB measurement is not limited to patients with normal LDL-C; it provides additional risk information in all patients, particularly those with discordance between particle number and cholesterol concentration.",

    "1196": "C is correct: The American Institute for Cancer Research recommends a comprehensive cancer prevention strategy including whole grains, vegetables, fruits, and beans; limiting ultra-processed foods, red and processed meat, sugar-sweetened beverages, and alcohol; maintaining a healthy weight; and being physically active—while specifically noting that supplements should not be used for cancer prevention. A is incorrect: Regular physical activity and limited red meat consumption are included in the recommendations but represent only a partial subset of the full AICR cancer prevention framework. B is incorrect: Dietary supplements are explicitly not recommended for cancer prevention by the AICR, and moderate alcohol consumption is to be limited, making this option directly contradictory to the guidelines. D is incorrect: Vitamin supplementation is specifically discouraged for cancer prevention by the AICR, and tobacco cessation alone does not represent the comprehensive dietary and lifestyle approach recommended.",

    "1197": "C is correct: The PAM measures multiple domains of patient engagement including self-management of illness, maintenance of function, involvement in treatment choices, collaboration with providers, selection of quality providers, and ability to navigate the healthcare system; a decline in score warrants assessment across all these dimensions. A is incorrect: Evaluating only medication adherence and vital signs addresses limited clinical parameters and misses the behavioural, collaborative, and navigational domains that the PAM is designed to measure. B is incorrect: Assessing only exercise habits and dietary patterns captures two lifestyle behaviours but neglects the broader domains of healthcare engagement, self-efficacy, and system navigation that PAM scores reflect. D is incorrect: Tracking appointment attendance and lab completion addresses access and compliance but does not evaluate the self-management confidence, treatment involvement, or provider collaboration dimensions that the PAM assesses.",

    "1198": "C is correct: The Lifestyle Heart Trial demonstrated that intensive lifestyle changes—including a low-fat vegetarian diet, aerobic exercise, stress management, and group support—produced regression of coronary atherosclerosis and reduction in anginal episodes after one year, with further regression at five years, without the use of lipid-lowering medications. A is incorrect: The trial demonstrated that medication management alone was inferior; control group patients who received usual care showed progression of atherosclerosis and more than twice as many cardiac events compared to the lifestyle intervention group. B is incorrect: The trial did not find lifestyle changes and medications to be equally effective; the comprehensive lifestyle programme produced regression while control patients showed progression—a clear difference in outcomes. D is incorrect: The trial found a clear and significant difference between intervention and control groups, with the lifestyle group showing regression and the control group showing progression of atherosclerosis.",
}


def main():
    data = json.loads(FILE.read_text(encoding="utf-8"))

    updated = 0
    for q in data:
        qid = str(q.get("question_id", ""))
        if qid in ENHANCED:
            q["rationale"] = ENHANCED[qid]
            updated += 1

    FILE.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"Updated {updated} rationales in {FILE.name}")

    # Verify
    data2 = json.loads(FILE.read_text(encoding="utf-8"))
    still_short = [q["question_id"] for q in data2 if "incorrect" not in q.get("rationale", "").lower()]
    print(f"{len(data2)} questions total, {len(still_short)} still need enhancement: {still_short}")


if __name__ == "__main__":
    main()
