import json
from collections import Counter

supplementary_tags = {
    '1118': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '1119': ['sedentary-behavior'],
    '1120': ['physical-activity', 'exercise-prescription'],
    '1121': ['physician-health', 'physical-activity'],
    '1122': ['physical-activity', 'exercise-prescription'],
    '1123': ['physical-activity', 'clinical-evidence'],
    '1124': ['clinical-assessment-tools', 'physical-activity'],
    '1125': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '1126': ['physical-activity', 'clinical-evidence'],
    '1127': ['physical-activity', 'exercise-prescription'],
    '1138': ['clinical-assessment-tools', 'physical-activity'],
    '1139': ['sedentary-behavior', 'physical-activity'],
    '1140': ['clinical-assessment-tools', 'physical-activity'],
    '1141': ['clinical-assessment-tools', 'physical-activity'],
    '1142': ['exercise-prescription', 'physical-activity'],
}

general_tags = {
    '00259': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00260': ['physical-activity'],
    '00261': ['physical-activity', 'exercise-prescription', 'weight-management'],
    '00262': ['physical-activity', 'exercise-prescription', 'hypertension'],
    '00263': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00264': ['physical-activity', 'diabetes'],
    '00265': ['physical-activity', 'exercise-prescription'],
    '00266': ['physical-activity', 'behavior-change-models'],
    '00267': ['physical-activity', 'cardiovascular-disease'],
    '00268': ['physical-activity', 'exercise-prescription'],
    '00269': ['physical-activity', 'cardiovascular-disease'],
    '00270': ['physical-activity', 'guideline-recommendations'],
    '00271': ['physician-health', 'physical-activity'],
    '00272': ['clinical-assessment-tools'],
    '00273': ['clinical-assessment-tools', 'physical-activity'],
    '00274': ['physical-activity'],
    '00275': ['physical-activity', 'exercise-prescription'],
    '00276': ['physical-activity', 'exercise-prescription'],
    '00277': ['clinical-assessment-tools', 'physical-activity'],
    '00278': ['physical-activity', 'exercise-prescription'],
    '00279': ['clinical-assessment-tools'],
    '00280': ['clinical-assessment-tools', 'physical-activity'],
    '00281': ['guideline-recommendations', 'physical-activity'],
    '00282': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00283': ['physical-activity', 'exercise-prescription'],
    '00284': ['physical-activity', 'exercise-prescription'],
    '00285': ['physical-activity', 'diabetes'],
    '00286': ['physical-activity', 'exercise-prescription'],
    '00287': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00288': ['physical-activity', 'clinical-evidence'],
    '00289': ['physical-activity', 'cardiovascular-disease'],
    '00290': ['physical-activity'],
    '00291': ['physical-activity', 'diabetes'],
    '00292': ['physical-activity', 'exercise-prescription'],
    '00293': ['physical-activity', 'exercise-prescription'],
    '00294': ['physical-activity', 'weight-management'],
    '00295': ['physical-activity', 'exercise-prescription'],
    '00296': ['physical-activity', 'cancer'],
    '00297': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00298': ['physical-activity', 'cancer'],
    '00299': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00300': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00301': ['physical-activity'],
    '00302': ['physical-activity', 'exercise-prescription'],
    '00303': ['exercise-prescription'],
    '00304': ['physical-activity', 'diabetes', 'clinical-evidence'],
    '00305': ['sedentary-behavior'],
    '00306': ['physical-activity', 'exercise-prescription'],
    '00307': ['clinical-assessment-tools', 'physical-activity'],
    '00308': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00309': ['physical-activity', 'weight-management'],
    '00310': ['physical-activity', 'exercise-prescription'],
    '00311': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00312': ['physical-activity', 'cancer'],
    '00313': ['physical-activity', 'exercise-prescription'],
    '00314': ['physical-activity', 'epidemiology-and-burden'],
    '00315': ['physical-activity', 'diabetes'],
    '00316': ['physical-activity', 'exercise-prescription'],
    '00317': ['physical-activity'],
    '00318': ['sedentary-behavior', 'physical-activity'],
    '00319': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00320': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00321': ['physical-activity', 'exercise-prescription'],
    '00322': ['physical-activity', 'exercise-prescription'],
    '00323': ['physical-activity', 'exercise-prescription'],
    '00324': ['physical-activity'],
    '00325': ['physical-activity', 'clinical-assessment-tools'],
    '00326': ['physical-activity', 'weight-management'],
    '00327': ['physical-activity', 'guideline-recommendations'],
    '00328': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00329': ['physical-activity', 'diabetes', 'behavior-change-models'],
    '00330': ['physical-activity', 'exercise-prescription'],
    '00331': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00332': ['physical-activity', 'exercise-prescription'],
    '00333': ['physical-activity', 'exercise-prescription'],
    '00334': ['physical-activity', 'diabetes', 'behavior-change-models', 'weight-management'],
    '00335': ['physical-activity', 'exercise-prescription'],
    '00336': ['physical-activity', 'exercise-prescription'],
    '00337': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00338': ['physical-activity', 'weight-management', 'exercise-prescription'],
    '00339': ['physical-activity', 'hypertension', 'behavior-change-models'],
    '00340': ['physical-activity', 'exercise-prescription'],
    '00341': ['clinical-assessment-tools', 'physical-activity', 'diabetes'],
    '00342': ['physical-activity', 'social-determinants', 'weight-management'],
    '00343': ['physical-activity', 'cardiovascular-disease'],
    '00344': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00345': ['physical-activity', 'exercise-prescription'],
    '00346': ['physical-activity', 'exercise-prescription'],
    '00347': ['physical-activity', 'exercise-prescription'],
    '00348': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00349': ['physical-activity', 'exercise-prescription'],
    '00350': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00351': ['physical-activity', 'exercise-prescription'],
    '00352': ['physical-activity', 'cardiovascular-disease'],
    '00353': ['physical-activity', 'exercise-prescription'],
    '00354': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00355': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00356': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00357': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00358': ['physical-activity', 'exercise-prescription'],
    '00359': ['physical-activity', 'exercise-prescription'],
    '00360': ['physical-activity', 'cardiovascular-disease', 'exercise-prescription'],
    '00361': ['physical-activity', 'diabetes', 'exercise-prescription'],
    '00362': ['physical-activity', 'weight-management'],
    '00363': ['physical-activity', 'exercise-prescription'],
}

study_tags = {
    '00666': ['physical-activity', 'clinical-evidence'],
    '00667': ['physical-activity', 'epidemiology-and-burden', 'clinical-evidence'],
    '00668': ['sedentary-behavior', 'clinical-evidence'],
    '00669': ['diabetes', 'physical-activity', 'clinical-evidence'],
    '00670': ['cardiovascular-disease', 'physical-activity', 'clinical-evidence'],
    '00671': ['physical-activity', 'clinical-evidence'],
    '00672': ['sedentary-behavior', 'clinical-evidence'],
    '00673': ['physical-activity', 'cancer', 'clinical-evidence'],
    '00674': ['cardiovascular-disease', 'weight-management', 'clinical-evidence'],
    '00675': ['physical-activity', 'clinical-evidence'],
    '00676': ['physical-activity', 'weight-management', 'diabetes', 'clinical-evidence'],
    '00677': ['physical-activity', 'clinical-evidence'],
    '00678': ['physical-activity', 'clinical-evidence'],
    '00679': ['diabetes', 'physical-activity', 'clinical-evidence'],
    '00680': ['sedentary-behavior', 'clinical-evidence'],
    '00681': ['diabetes', 'physical-activity', 'clinical-evidence'],
    '00682': ['cardiovascular-disease', 'physical-activity', 'clinical-evidence'],
    '00683': ['physical-activity', 'clinical-evidence'],
    '00684': ['sedentary-behavior', 'physical-activity', 'clinical-evidence'],
    '00685': ['physical-activity', 'clinical-evidence'],
    '00686': ['cardiovascular-disease', 'clinical-evidence'],
    '00687': ['physical-activity', 'clinical-evidence'],
    '00688': ['physical-activity', 'clinical-evidence'],
    '00689': ['cancer', 'physical-activity', 'clinical-evidence'],
    '00690': ['sedentary-behavior', 'clinical-evidence'],
    '00691': ['diabetes', 'physical-activity', 'clinical-evidence'],
    '00692': ['cardiovascular-disease', 'physical-activity', 'clinical-evidence'],
    '00693': ['physical-activity', 'clinical-evidence'],
    '00694': ['sedentary-behavior', 'physical-activity', 'clinical-evidence'],
    '00695': ['physical-activity', 'clinical-evidence'],
    '00696': ['cardiovascular-disease', 'weight-management', 'clinical-evidence'],
    '00697': ['physical-activity', 'clinical-evidence'],
    '00698': ['weight-management', 'diabetes', 'clinical-evidence'],
    '00699': ['physical-activity', 'clinical-evidence'],
    '00700': ['physical-activity', 'diabetes', 'clinical-evidence'],
    '00701': ['physical-activity', 'clinical-evidence'],
    '00702': ['clinical-assessment-tools', 'physical-activity', 'clinical-evidence'],
    '00703': ['clinical-assessment-tools', 'physical-activity', 'clinical-evidence'],
    '00704': ['exercise-prescription', 'clinical-evidence'],
    '00705': ['clinical-assessment-tools', 'exercise-prescription', 'clinical-evidence'],
    '00706': ['clinical-assessment-tools', 'exercise-prescription', 'clinical-evidence'],
    '00707': ['clinical-assessment-tools', 'clinical-evidence'],
    '00708': ['clinical-assessment-tools', 'exercise-prescription', 'clinical-evidence'],
    '00709': ['exercise-prescription', 'clinical-evidence'],
    '00710': ['clinical-assessment-tools', 'exercise-prescription', 'clinical-evidence'],
    '00711': ['clinical-assessment-tools', 'guideline-recommendations', 'clinical-evidence'],
    '00712': ['clinical-assessment-tools', 'exercise-prescription', 'clinical-evidence'],
    '00713': ['clinical-assessment-tools', 'cardiovascular-disease', 'clinical-evidence'],
    '00714': ['exercise-prescription', 'clinical-evidence'],
    '00715': ['exercise-prescription', 'clinical-evidence'],
    '00716': ['clinical-assessment-tools', 'exercise-prescription', 'clinical-evidence'],
    '00717': ['exercise-prescription', 'clinical-evidence'],
    '00718': ['clinical-assessment-tools', 'exercise-prescription', 'clinical-evidence'],
    '00719': ['exercise-prescription', 'clinical-evidence'],
}

base = 'C:/Python Projects/cc-qb/data'
all_questions = []

files = [
    ('From Board Review Notes -  - 6. Physical Activity Science and Prescription.json', supplementary_tags),
    ('General - 6. Physical Activity Science and Prescription.json', general_tags),
    ('Study-Tool Based - 6. Physical Activity Science and Prescription.json', study_tags),
]

for fname, tag_map in files:
    with open(f'{base}/{fname}', encoding='utf-8') as f:
        questions = json.load(f)
    for q in questions:
        qid = str(q['question_id'])
        q['question_id'] = qid
        q['tags'] = tag_map.get(qid, [])
        q['source_file'] = fname
        all_questions.append(q)

all_questions.sort(key=lambda q: q['question_id'].zfill(6))

out = f'{base}/consolidated/06-physical-activity-science-and-prescription.json'
with open(out, 'w') as f:
    json.dump(all_questions, f, indent=2)

print(f'Written {len(all_questions)} questions')
tag_counts = Counter(t for q in all_questions for t in q['tags'])
for tag, count in sorted(tag_counts.items(), key=lambda x: -x[1]):
    print(f'  {tag}: {count}')
