import json
from collections import Counter

supplementary_tags = {
    '1099': ['dietary-patterns', 'diabetes', 'nutrition-science'],
    '1100': ['dietary-patterns', 'weight-management'],
    '1101': ['dietary-patterns', 'cardiovascular-disease', 'clinical-evidence'],
    '1102': ['nutrition-science', 'diabetes'],
    '1103': ['dietary-patterns', 'clinical-evidence'],
    '1104': ['nutrition-science', 'clinical-evidence'],
    '1105': ['dietary-patterns', 'micronutrients'],
    '1106': ['dietary-patterns', 'cardiovascular-disease', 'clinical-evidence'],
    '1107': ['diabetes', 'dietary-patterns'],
    '1108': ['dietary-patterns', 'cardiovascular-disease', 'clinical-evidence'],
    '1109': ['nutrition-science', 'clinical-evidence'],
    '1110': ['clinical-assessment-tools'],
    '1111': ['micronutrients', 'dietary-patterns'],
    '1112': ['food-preparation'],
    '1113': ['dietary-patterns', 'cardiovascular-disease', 'clinical-evidence'],
    '1114': ['food-preparation', 'guideline-recommendations'],
    '1115': ['cardiovascular-disease', 'nutrition-science', 'clinical-evidence'],
    '1116': ['dietary-patterns', 'weight-management', 'clinical-evidence'],
    '1117': ['dietary-patterns', 'clinical-evidence'],
    '1118': ['guideline-recommendations'],
}

general_tags = {
    '00158': ['dietary-patterns', 'diabetes', 'hypertension'],
    '00159': ['weight-management', 'dietary-patterns'],
    '00160': ['cardiovascular-disease', 'dietary-patterns'],
    '00161': ['diabetes', 'dietary-patterns'],
    '00162': ['hypertension', 'dietary-patterns'],
    '00163': ['cancer', 'dietary-patterns'],
    '00164': ['cardiovascular-disease', 'dietary-patterns', 'micronutrients'],
    '00165': ['micronutrients', 'dietary-patterns'],
    '00166': ['cardiovascular-disease', 'dietary-patterns'],
    '00167': ['cancer', 'dietary-patterns'],
    '00168': ['dietary-patterns', 'weight-management'],
    '00169': ['nutrition-science', 'diabetes'],
    '00170': ['micronutrients'],
    '00171': ['hypertension', 'micronutrients'],
    '00172': ['micronutrients', 'dietary-patterns'],
    '00173': ['nutrition-science', 'cardiovascular-disease'],
    '00174': ['cancer', 'dietary-patterns'],
    '00175': ['cardiovascular-disease', 'micronutrients'],
    '00176': ['micronutrients', 'dietary-patterns'],
    '00177': ['nutrition-science', 'diabetes'],
    '00178': ['cardiovascular-disease', 'dietary-patterns'],
    '00179': ['micronutrients', 'dietary-patterns'],
    '00180': ['nutrition-science', 'diabetes'],
    '00181': ['hypertension', 'dietary-patterns'],
    '00182': ['nutrition-science', 'cardiovascular-disease'],
    '00183': ['dietary-patterns', 'weight-management'],
    '00184': ['cancer', 'dietary-patterns'],
    '00185': ['dietary-patterns'],
    '00186': ['micronutrients'],
    '00187': ['dietary-patterns'],
    '00188': ['dietary-patterns', 'cardiovascular-disease', 'clinical-evidence'],
    '00189': ['diabetes', 'clinical-evidence'],
    '00190': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00191': ['dietary-patterns', 'clinical-evidence'],
    '00192': ['hypertension', 'dietary-patterns', 'clinical-evidence'],
    '00193': ['cardiovascular-disease', 'clinical-evidence'],
    '00194': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00195': ['dietary-patterns', 'weight-management', 'clinical-evidence'],
    '00196': ['diabetes', 'dietary-patterns', 'clinical-evidence'],
    '00197': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00198': ['guideline-recommendations', 'nutrition-science'],
    '00199': ['guideline-recommendations'],
    '00200': ['nutrition-science'],
    '00201': ['clinical-assessment-tools'],
    '00202': ['guideline-recommendations'],
    '00203': ['guideline-recommendations', 'micronutrients'],
    '00204': ['guideline-recommendations', 'nutrition-science'],
    '00205': ['food-preparation'],
    '00206': ['guideline-recommendations'],
    '00207': ['nutrition-science'],
    '00208': ['food-preparation'],
    '00209': ['micronutrients', 'food-preparation'],
    '00210': ['food-preparation'],
    '00211': ['micronutrients', 'dietary-patterns'],
    '00212': ['motivational-interviewing'],
    '00213': ['nutrition-science', 'diabetes'],
    '00214': ['nutrition-science'],
    '00215': ['dietary-patterns'],
    '00216': ['food-preparation'],
    '00217': ['micronutrients'],
    '00218': ['micronutrients', 'dietary-patterns'],
    '00219': ['diabetes', 'dietary-patterns'],
    '00220': ['planetary-health', 'dietary-patterns'],
    '00221': ['cancer', 'dietary-patterns'],
    '00222': ['hypertension', 'nutrition-science'],
    '00223': ['weight-management'],
    '00224': ['micronutrients', 'dietary-patterns'],
    '00225': ['cardiovascular-disease', 'micronutrients'],
    '00226': ['nutrition-science', 'physical-activity'],
    '00227': ['micronutrients'],
    '00228': ['micronutrients'],
    '00229': ['community-advocacy', 'micronutrients'],
    '00230': ['cardiovascular-disease', 'dietary-patterns'],
    '00231': ['diabetes', 'dietary-patterns'],
    '00232': ['hypertension', 'dietary-patterns'],
    '00233': ['micronutrients', 'dietary-patterns'],
    '00234': ['cardiovascular-disease', 'dietary-patterns'],
    '00235': ['cardiovascular-disease', 'dietary-patterns'],
    '00236': ['hypertension', 'guideline-recommendations'],
    '00237': ['micronutrients'],
    '00238': ['weight-management', 'dietary-patterns'],
    '00239': ['cancer', 'dietary-patterns'],
    '00240': ['cardiovascular-disease', 'micronutrients'],
    '00241': ['micronutrients', 'dietary-patterns'],
    '00242': ['diabetes', 'dietary-patterns'],
    '00243': ['cancer', 'dietary-patterns'],
    '00244': ['hypertension', 'micronutrients'],
    '00245': ['micronutrients'],
    '00246': ['food-preparation'],
    '00247': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00248': ['micronutrients', 'physical-activity'],
    '00249': ['community-advocacy', 'planetary-health'],
    '00250': ['micronutrients'],
    '00251': ['community-advocacy', 'micronutrients'],
    '00252': ['food-preparation'],
    '00253': ['micronutrients'],
    '00254': ['food-preparation', 'nutrition-science'],
    '00255': ['micronutrients', 'dietary-patterns'],
    '00256': ['dietary-patterns'],
    '00257': ['micronutrients'],
    '00258': ['food-preparation'],
}

study_tags = {
    '00613': ['dietary-patterns', 'clinical-evidence'],
    '00614': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00615': ['dietary-patterns', 'clinical-evidence'],
    '00616': ['dietary-patterns', 'clinical-evidence'],
    '00617': ['dietary-patterns', 'clinical-evidence'],
    '00618': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00619': ['cardiovascular-disease', 'clinical-evidence'],
    '00620': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00621': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00622': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00623': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00624': ['dietary-patterns', 'clinical-evidence'],
    '00625': ['cancer', 'clinical-evidence'],
    '00626': ['weight-management', 'dietary-patterns', 'clinical-evidence'],
    '00627': ['cancer', 'dietary-patterns', 'clinical-evidence'],
    '00628': ['weight-management', 'dietary-patterns', 'clinical-evidence'],
    '00629': ['cancer', 'dietary-patterns', 'clinical-evidence'],
    '00630': ['cardiovascular-disease', 'clinical-evidence'],
    '00631': ['cardiovascular-disease', 'hypertension', 'clinical-evidence'],
    '00632': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00633': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00634': ['nutrition-science', 'clinical-evidence'],
    '00635': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00636': ['hypertension', 'nutrition-science', 'clinical-evidence'],
    '00637': ['hypertension', 'dietary-patterns', 'clinical-evidence'],
    '00638': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00639': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00640': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00641': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00642': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00643': ['dietary-patterns', 'clinical-evidence'],
    '00644': ['dietary-patterns', 'clinical-evidence'],
    '00645': ['dietary-patterns', 'clinical-evidence'],
    '00646': ['cardiovascular-disease', 'clinical-evidence'],
    '00647': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00648': ['nutrition-science', 'clinical-evidence'],
    '00649': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00650': ['hypertension', 'nutrition-science', 'clinical-evidence'],
    '00651': ['hypertension', 'dietary-patterns', 'clinical-evidence'],
    '00652': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00653': ['cancer', 'dietary-patterns', 'clinical-evidence'],
    '00654': ['clinical-evidence'],
    '00655': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00656': ['clinical-evidence'],
    '00657': ['clinical-evidence'],
    '00658': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00659': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00660': ['food-preparation', 'clinical-evidence'],
    '00661': ['cardiovascular-disease', 'dietary-patterns', 'clinical-evidence'],
    '00662': ['dietary-patterns', 'clinical-evidence'],
    '00663': ['cancer', 'micronutrients', 'clinical-evidence'],
    '00664': ['cancer', 'dietary-patterns', 'clinical-evidence'],
    '00665': ['dietary-patterns', 'clinical-evidence'],
}

base = 'C:/Python Projects/cc-qb/data'
all_questions = []

files = [
    ('From Board Review Notes -  - 5. Nutrition Science Assessment and Prescription Guidelines.json', supplementary_tags),
    ('General - 5. Nutrition Science Assessment and Prescription Guidelines.json', general_tags),
    ('Study-Tool Based - 5. Nutrition Science Assessment and Prescription Guidelines.json', study_tags),
]

for fname, tag_map in files:
    with open(f'{base}/{fname}', encoding='utf-8') as f:
        questions = json.load(f)
    for q in questions:
        qid = str(q['question_id'])
        q['question_id'] = qid
        q['tags'] = tag_map.get(qid, [])
        q['source_file'] = fname
        all_questions.append(q)

all_questions.sort(key=lambda q: q['question_id'].zfill(6))

out = f'{base}/consolidated/05-nutrition-science-assessment-and-prescription-guidelines.json'
with open(out, 'w') as f:
    json.dump(all_questions, f, indent=2)

print(f'Written {len(all_questions)} questions')
tag_counts = Counter(t for q in all_questions for t in q['tags'])
for tag, count in sorted(tag_counts.items(), key=lambda x: -x[1]):
    print(f'  {tag}: {count}')
